image: mischief/docker-golang
env:
    - GOPATH=/var/cache/drone
    - PATH=$GOPATH/bin:$GOROOT/bin:$PATH
script:
    - cd .. && mv vip /var/cache/drone/src
    - cd /var/cache/drone/src/vip
    - apt-get update -qq
    - apt-get -y install bzr mercurial
    - go get
    - go get -t
    - go build
    - go test -gocheck.v
    - go test -gocheck.v -gocheck.b
