image: docker.vokalinteractive.com/golang:latest
env:
    - GOPATH=/var/cache/drone
script:
    - apt-get -y install bzr mercurial
    - go get
    - go get -t
    - go build
    - go test -gocheck.v
services:
    - mongodb
