image: mischief/docker-golang
env:
    - GOPATH=/var/cache/drone
script:
    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
    - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | tee /etc/apt/sources.list.d/mongodb.list
    - apt-get update
    - apt-get -y install bzr mercurial mongodb-10gen
    - go get
    - go get -t
    - go build
    - go test -gocheck.v
service:
    - mongodb
