image: bradrydzewski/go:1.3
env:
    - GOPATH=/var/cache/drone
    - PATH=$GOPATH/bin:$GOROOT/bin:$PATH
script:
    - cd .. && mv vip /var/cache/drone/src
    - cd /var/cache/drone/src/vip
    - sudo apt-get update -qq
    - sudo apt-get -y install bzr mercurial
    - go get
    - go get -t
    - go build
    - go test -gocheck.v
    - go test -gocheck.v -gocheck.b
    - cd fetch && go test -v
    - cd ..
publish:
    docker:
        docker_server: docker-build.vokalinteractive.com
        docker_host: tcp://docker-build.vokalinteractive.com:2375
        docker_port: 2375
        docker_version: 1.3.0
        registry_login_url: https://docker.vokalinteractive.com/v1/
        registry_login: true
        username: $$dockerUsername
        password: $$dockerPassword
        email: docker@vokalinteractive.com
        image_name: docker.vokalinteractive.com/vip
        tags: [latest]
        push_latest: true
notify:
    webhook:
        urls:
            - https://dronebot.vokalinteractive.com/hook
        on_success: true
        on_failure: true
