image: bradrydzewski/go:1.3
env:
    - GOPATH=/var/cache/drone
    - PATH=$GOPATH/bin:$GOROOT/bin:$PATH
script:
    - cd .. && mv vip /var/cache/drone/src
    - cd /var/cache/drone/src/vip
    - sudo apt-get update -qq
    - sudo apt-get -y install bzr mercurial python-pip libvips-dev
    - go get
    - go get -t
    - go build
    - go test -gocheck.v
    - go test -gocheck.v -gocheck.b -coverprofile=coverage.txt -covermode=count
    - cd fetch && go test -v -coverprofile=coverage.txt -covermode=count
    - cd ..
    - cat fetch/coverage.txt >> coverage.txt
    - sudo pip install codecov
    - codecov --token=$$codecovToken
publish:
    docker:
        docker_server: docker-build.vokal.io
        docker_host: tcp://docker-build.vokal.io:2375
        docker_port: 2375
        docker_version: 1.4.1
        registry_login_url: https://docker.vokal.io/v1/
        registry_login: true
        username: $$dockerUsername
        password: $$dockerPassword
        email: docker@vokal.io
        image_name: docker.vokal.io/vip
        tags: [latest]
        push_latest: true
notify:
    webhook:
        urls:
            - https://dronebot.vokal.io/hook
        on_success: true
        on_failure: true
