image: mischief/docker-golang
env:
    - GOPATH=/var/cache/drone
script:
    - apt-get -y install bzr mercurial
    - mkdir -p /var/cache/drone/src/github.com/vokalinteractive
    - ln -s . /var/cache/drone/src/github.com/vokalinteractive/vip
    - go get
    - go get -t
    - go build
    - go test -gocheck.v
services:
    - mongodb
    - postgres
